---
apiVersion: v1
data:  
  mirror-registry-vranmgmt1.fyre.ibm.com..5000: |
    -----BEGIN CERTIFICATE-----
    MIIDrzCCApegAwIBAgIUeSzFFZbc+jLTFUn47zDsF5UNnYowDQYJKoZIhvcNAQEL
    BQAwZzELMAkGA1UEBhMCSU4xCzAJBgNVBAgMAktBMQswCQYDVQQHDAJTWjENMAsG
    A1UECgwESUJNLjEvMC0GA1UEAwwmbWlycm9yLXJlZ2lzdHJ5LXZyYW5tZ210MS5m
    eXJlLmlibS5jb20wHhcNMjEwODI0MDA1MTA0WhcNMzEwODIyMDA1MTA0WjBnMQsw
    CQYDVQQGEwJJTjELMAkGA1UECAwCS0ExCzAJBgNVBAcMAlNaMQ0wCwYDVQQKDARJ
    Qk0uMS8wLQYDVQQDDCZtaXJyb3ItcmVnaXN0cnktdnJhbm1nbXQxLmZ5cmUuaWJt
    LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM1sX7jvpgTC/Ccw
    sMzbaHAVZiEarw6JJwXyv1STUpecDkbN95VRHNIKYxLmZJlkB1QuE15dxWTz8CfO
    47ZHCkUTIie7BmaBLrCKOp+BvxReDD2fbIeYOjOolnowniXJyJJlqeixxV045xQA
    v2JQMATjZ++4vs3R76lPvXeIH4oRMF70bthmCeqBqHMfyWdcsIugrCenrZmJm6PA
    FW81hbEnlR9eaeYbnw5786RnJyoVGGvyHjeLZ1ruMo1E7KaSX7LSJokN/x3aBXdB
    z1tc4YOQrG4jn1XhbYCEE11Ru7d/Z7UXJOi4xI3W1zNYHW1Swt4g+p70Q3Xyq9Mh
    2IqhGocCAwEAAaNTMFEwHQYDVR0OBBYEFF6j8cAZi+TgDRX3WEnUv7mHp6ECMB8G
    A1UdIwQYMBaAFF6j8cAZi+TgDRX3WEnUv7mHp6ECMA8GA1UdEwEB/wQFMAMBAf8w
    DQYJKoZIhvcNAQELBQADggEBAEhBEaI3jGPB/8k6h3lM15XgbS7ziqaN4QzRZcid
    2xcMP9tFIZJqzukCxt0clO/lzOX399RpjH4C/470teTOE81tCeP5n57TR1ntlmah
    /4VOR7jfjmCHGV2lDRu22QTSfaSKq7ACspwi046Oc1r+JXzeQz3V6ZXV7Z+EM4zs
    s+3MWLVHZYf/dBFhcNND2XJ4nvtLgqwbdS2ZF1sLjLlMuGu1KqwyiUZyxZpm6h4J
    +UYgDnC40yVxaNk7Z/xFoCuTijslszFsn+18PkHhXIbAnc4x2kV6xjfypozy1rzx
    P4W7kupi5Id9iFqBdCDP7kA37sjIeT5C3vE7f5HTQKa6Nx4=
    -----END CERTIFICATE-----
    -----BEGIN CERTIFICATE-----
    MIIDrzCCApegAwIBAgIUeSzFFZbc+jLTFUn47zDsF5UNnYowDQYJKoZIhvcNAQEL
    BQAwZzELMAkGA1UEBhMCSU4xCzAJBgNVBAgMAktBMQswCQYDVQQHDAJTWjENMAsG
    A1UECgwESUJNLjEvMC0GA1UEAwwmbWlycm9yLXJlZ2lzdHJ5LXZyYW5tZ210MS5m
    eXJlLmlibS5jb20wHhcNMjEwODI0MDA1MTA0WhcNMzEwODIyMDA1MTA0WjBnMQsw
    CQYDVQQGEwJJTjELMAkGA1UECAwCS0ExCzAJBgNVBAcMAlNaMQ0wCwYDVQQKDARJ
    Qk0uMS8wLQYDVQQDDCZtaXJyb3ItcmVnaXN0cnktdnJhbm1nbXQxLmZ5cmUuaWJt
    LmNvbTCCASIwDQYJKoZIhvcNAQEBBQADggEPADCCAQoCggEBAM1sX7jvpgTC/Ccw
    sMzbaHAVZiEarw6JJwXyv1STUpecDkbN95VRHNIKYxLmZJlkB1QuE15dxWTz8CfO
    47ZHCkUTIie7BmaBLrCKOp+BvxReDD2fbIeYOjOolnowniXJyJJlqeixxV045xQA
    v2JQMATjZ++4vs3R76lPvXeIH4oRMF70bthmCeqBqHMfyWdcsIugrCenrZmJm6PA
    FW81hbEnlR9eaeYbnw5786RnJyoVGGvyHjeLZ1ruMo1E7KaSX7LSJokN/x3aBXdB
    z1tc4YOQrG4jn1XhbYCEE11Ru7d/Z7UXJOi4xI3W1zNYHW1Swt4g+p70Q3Xyq9Mh
    2IqhGocCAwEAAaNTMFEwHQYDVR0OBBYEFF6j8cAZi+TgDRX3WEnUv7mHp6ECMB8G
    A1UdIwQYMBaAFF6j8cAZi+TgDRX3WEnUv7mHp6ECMA8GA1UdEwEB/wQFMAMBAf8w
    DQYJKoZIhvcNAQELBQADggEBAEhBEaI3jGPB/8k6h3lM15XgbS7ziqaN4QzRZcid
    2xcMP9tFIZJqzukCxt0clO/lzOX399RpjH4C/470teTOE81tCeP5n57TR1ntlmah
    /4VOR7jfjmCHGV2lDRu22QTSfaSKq7ACspwi046Oc1r+JXzeQz3V6ZXV7Z+EM4zs
    s+3MWLVHZYf/dBFhcNND2XJ4nvtLgqwbdS2ZF1sLjLlMuGu1KqwyiUZyxZpm6h4J
    +UYgDnC40yVxaNk7Z/xFoCuTijslszFsn+18PkHhXIbAnc4x2kV6xjfypozy1rzx
    P4W7kupi5Id9iFqBdCDP7kA37sjIeT5C3vE7f5HTQKa6Nx4=
    -----END CERTIFICATE-----
kind: ConfigMap
metadata:
  name: quay-vranqamgmt-config
  namespace: openshift-config